"""
Handler Discovery Engine — Single source of truth for loading user code.

Consolidates the handler discovery logic into one robust module that works
across ALL platforms:
  - Desktop (pywebview): backend/ found via pywebapp.json project root
  - Web (Flask): same as desktop
  - Android (Chaquopy bundled): backend/ is inside APK assets, not on filesystem
  - Android (dev mode): backend/ pushed to /data/local/tmp/pywebapp/python/ via ADB
  - Frozen (PyInstaller): backend/ bundled inside the executable

Strategy:
    1. Try importlib.import_module("backend") — works universally because
       Chaquopy's AssetFinder, sys.path entries, and PyInstaller hooks all 
       support this. This is the PRIMARY method.
    2. If that fails, search the filesystem for backend/ (fallback for edge cases)
    3. Walk all sub-modules with isolation (one failure doesn't break the rest)
"""

import importlib
import importlib.util
import os
import pkgutil
import sys
import threading
import traceback

from pywebapp.core.logger import get_logger

logger = get_logger("discovery")

_discovered = False
# FIXED: BUG C — Private lock for discovery to prevent TOCTOU race
_discovery_lock = threading.Lock()


def _find_project_root() -> str:
    """Search upwards for pywebapp.json to find the project anchor."""
    curr = os.getcwd()
    while curr != os.path.dirname(curr):
        if os.path.exists(os.path.join(curr, "pywebapp.json")):
            return curr
        curr = os.path.dirname(curr)
    return os.getcwd()


def _try_import_backend():
    """
    Try to import the 'backend' package using Python's standard import system.
    """
    try:
        backend = importlib.import_module("backend")
        logger.info(f"[Discovery] Imported 'backend' via standard import: {getattr(backend, '__file__', 'bundled')}")
        return backend
    except ImportError:
        pass
    
    return None


def _try_path_import_backend():
    """
    Fallback: Try to find and import backend/ from the filesystem directly.
    Used when the standard import fails.
    """
    # 1. Check project root (anchored by pywebapp.json)
    project_root = os.path.abspath(os.path.normpath(_find_project_root()))
    candidate = os.path.join(project_root, "backend")
    
    # 2. Also check sys.path entries
    search_dirs = [candidate]
    for path_entry in sys.path:
        search_dirs.append(os.path.join(path_entry, "backend"))
    
    for backend_path in search_dirs:
        if not os.path.isdir(backend_path):
            continue
        
        # Ensure __init__.py exists
        init_file = os.path.join(backend_path, "__init__.py")
        if not os.path.exists(init_file):
            try:
                with open(init_file, "w") as f:
                    f.write("# Auto-generated by PyWebApp\n")
            except Exception:
                pass
        
        if not os.path.exists(init_file):
            continue
        
        try:
            spec = importlib.util.spec_from_file_location("backend", init_file,
                        submodule_search_locations=[backend_path])
            backend = importlib.util.module_from_spec(spec)
            sys.modules["backend"] = backend
            spec.loader.exec_module(backend)
            logger.info(f"[Discovery] Imported 'backend' via path: {backend_path}")
            return backend
        except Exception as e:
            logger.warning(f"[Discovery] Path import failed for {backend_path}: {e}")
            continue
    
    return None


def discover_handlers() -> bool:
    """
    Discover and import all user handlers from the backend/ package.
    Thread-safe implementation with double-checked locking.
    """
    global _discovered
    if _discovered:
        return True

    # FIXED: BUG C — Ensure EVERYTHING is inside the lock block
    with _discovery_lock:
        # Double-check pattern
        if _discovered:
            return True
        
        # === Strategy 1: Standard Python import (works everywhere) ===
        backend = _try_import_backend()
        
        # === Strategy 2: Filesystem path-based import (fallback) ===
        if backend is None:
            backend = _try_path_import_backend()
        
        # === Strategy 3: Legacy single-file handler (no backend/ package) ===
        if backend is None:
            found_legacy = False
            for target in ["backend.handlers", "handlers"]:
                try:
                    importlib.import_module(target)
                    logger.info(f"[Discovery] Loaded legacy handler: {target}")
                    found_legacy = True
                    break
                except ImportError:
                    continue
            
            if not found_legacy:
                logger.warning("[Discovery] No 'backend/' package found on any platform.")
            
            _discovered = True
            return found_legacy

        # === Walk and load sub-modules with ISOLATION ===
        loaded = 0
        try:
            for loader, module_name, is_pkg in pkgutil.walk_packages(
                backend.__path__, backend.__name__ + "."
            ):
                try:
                    importlib.import_module(module_name)
                    logger.debug(f"  ✅ {module_name}")
                    loaded += 1
                except Exception:
                    logger.warning(f"  ❌ {module_name} (FAILED)")
                    logger.debug(f"     {traceback.format_exc().splitlines()[-1]}")
                    continue
        except Exception as e:
            # pkgutil.walk_packages itself can fail on some platforms
            logger.warning(f"[Discovery] walk_packages failed: {e}")
            # Try direct import of backend.handlers as last resort
            try:
                importlib.import_module("backend.handlers")
                logger.info("[Discovery] Direct import of backend.handlers succeeded")
                loaded = 1
            except Exception as e2:
                logger.error(f"[Discovery] Direct import also failed: {e2}")

        _discovered = True
        logger.info(f"[Discovery] Loaded {loaded} handler module(s)")
        return loaded > 0
