"""
Handler Discovery Engine — Single source of truth for loading user code.

Consolidates the handler discovery logic that was duplicated between
api.py and server.py into one robust module.

Strategy:
    1. Search upward for pywebapp.json to find the project root
    2. Locate the backend/ package
    3. Ensure __init__.py exists (auto-create if needed)
    4. Import all sub-modules with isolation (one failure doesn't break the rest)
"""

import importlib
import importlib.util
import os
import pkgutil
import sys
import traceback

from pywebapp.core.logger import get_logger

logger = get_logger("discovery")

_discovered = False


def _find_project_root() -> str:
    """Search upwards for pywebapp.json to find the project anchor."""
    curr = os.getcwd()
    while curr != os.path.dirname(curr):
        if os.path.exists(os.path.join(curr, "pywebapp.json")):
            return curr
        curr = os.path.dirname(curr)
    return os.getcwd()


def discover_handlers() -> bool:
    """
    Discover and import all user handlers from the backend/ package.
    
    Uses path-direct imports for maximum robustness across all platforms
    (Desktop, Android/Chaquopy, frozen PyInstaller bundles).
    
    Returns True if any handlers were found and loaded.
    """
    global _discovered
    if _discovered:
        return True

    project_root = os.path.abspath(os.path.normpath(_find_project_root()))
    backend_path = os.path.join(project_root, "backend")

    if not os.path.isdir(backend_path):
        # Also try legacy "handlers" module (single-file projects)
        for target in ["handlers"]:
            try:
                importlib.import_module(target)
                logger.info(f"Discovered single-file handler: {target}")
                _discovered = True
                return True
            except ImportError:
                continue

        logger.warning("No 'backend/' directory found. Ensure your handlers are in 'backend/' or 'handlers.py'.")
        _discovered = True
        return False

    # Ensure __init__.py exists
    init_file = os.path.join(backend_path, "__init__.py")
    if not os.path.exists(init_file):
        try:
            with open(init_file, "w") as f:
                f.write("# Auto-generated by PyWebApp\n")
        except Exception:
            pass

    # Path-Direct Import (most robust across platforms)
    try:
        spec = importlib.util.spec_from_file_location("backend", init_file)
        backend = importlib.util.module_from_spec(spec)
        sys.modules["backend"] = backend
        spec.loader.exec_module(backend)
    except Exception as e:
        logger.error(f"Critical: Could not load 'backend' package from {backend_path}: {e}")
        _discovered = True
        return False

    logger.info(f"[Discovery] Active: {backend_path}")

    # Walk and load with ISOLATION — one failure doesn't break the rest
    loaded = 0
    for loader, module_name, is_pkg in pkgutil.walk_packages(backend.__path__, backend.__name__ + "."):
        try:
            importlib.import_module(module_name)
            logger.debug(f"  ✅ {module_name}")
            loaded += 1
        except Exception:
            logger.warning(f"  ❌ {module_name} (FAILED)")
            logger.debug(f"     Details: {traceback.format_exc().splitlines()[-1]}")
            continue

    _discovered = True
    logger.info(f"[Discovery] Loaded {loaded} handler module(s)")
    return loaded > 0
